# Generated by Django 4.2 on 2023-04-20 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Название')),
                ('title', models.CharField(max_length=30, null=True, verbose_name='Заголовок')),
                ('author', models.CharField(max_length=30, verbose_name='Автор')),
                ('description', models.TextField(max_length=512, null=True, verbose_name='Описание')),
                ('price', models.IntegerField(max_length=5, verbose_name='Цена')),
            ],
        ),
    ]
