# Generated by Django 4.2 on 2023-04-20 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, max_length=512, null=True, verbose_name='Описание'),
        ),
    ]
