# Generated by Django 4.2 on 2023-04-20 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_store', '0002_alter_book_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Заголовок'),
        ),
    ]
