# Generated by Django 4.2 on 2023-04-23 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_store', '0004_profile_alter_book_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Цена'),
        ),
    ]
